### ISSUE TITLE
Stockade 

### ISSUE THREAD

**Issue by Ace-wildhammer** [talamortis/azerothcore-classic#10]
Description of the Issue:
In the stockade the trash defias is behaving inproperly. After the party left and returnted in the instance, several of the defias who were previewsly aggroed appeared at the entrance. However by approaching them, thy did not reacted and could not be attacked. On second occasion after the party left the instance the defias followed them outside, which I am not sure if it should happen...

Instance: The Stockade
![report1 ace](https://cloud.githubusercontent.com/assets/26637435/24273016/c8bc3bbe-1028-11e7-9ff4-58801c8926d1.png)
![report2 ace](https://cloud.githubusercontent.com/assets/26637435/24273017/c8bf2e1e-1028-11e7-83f7-ad2373b7cf0a.png)

Seems the whole instance needs a touch. 

Cheers, 
-Ace

**Comment by talamortis** [comment]
the captive is an event it spawns creatures just outside of the instance, and then they run to the top to fight the guards
