### ISSUE TITLE
Buffing/Healing low level characters

### ISSUE THREAD

**Issue by Jenleigh** [talamortis/azerothcore-classic#11]
Description of the Issue:
On my 33 priest, I buffed a level 5 with Rank 5 Power word Fortitude.  After that, I was unable to use any spell on my action bar.  I couldn't even use my hearthstone in my bag.  The error I kept getting was "another action was in use".  Logging out fixes it.  Logged back in to heal with Rank 4 Renew.  Same results.  Relogged and healed him with Rank 1 Renew, and it was fine, Rank 2 Renew was fine.  Rank 3 and my action bars were unusable again.

QuestID/ BossID:

Instance:

What should happen:
I believe that ingame will just not let you cast a high rank spell on a lowbie.  You get a message in game, or your characters says "I cannot do that".

Faction: Horde/Alliance
Horde

How to repoduce:

**Comment by talamortis** [comment]
can't repoduce
