### ISSUE TITLE
Vilebranch Raiding Wolf

### ISSUE THREAD

**Issue by Sockerkorn** [talamortis/azerothcore-classic#16]
Description of the Issue:
I think they're bugged. I engaged it in combat, it did roughlt 400 dmg per hit, which makes sense i guess since it's an high level elite. However it did feel like it's attack speed was 0.4 - 0.5 ish per attack. Which feel's a bit too fast. Might wanna be worth checking out. They do More DPS than most 60 elites. 

QuestID/ BossID:

Instance:

What should happen:

Faction: Horde/Alliance

How to repoduce:

**Comment by talamortis** [comment]
Timer was incorrect, now set to attack every 2 seconds
