### ISSUE TITLE
Huntsman Malkhor's bones

### ISSUE THREAD

**Issue by Sockerkorn** [talamortis/azerothcore-classic#19]
Description of the Issue:
Dropped from a Jade Sludge. Should be lootable by the pit, not by the NPC's :>

QuestID/ BossID:

Instance:

What should happen:

Faction: Horde/Alliance

How to repoduce:

**Comment by talamortis** [comment]
http://db.vanillagaming.org/?item=19070#dropped-by

**Comment by talamortis** [comment]
after doing some research the statement is correct.
