### ISSUE TITLE
Counterattack! 

### ISSUE THREAD

**Issue by Dreask** [talamortis/azerothcore-classic#30]
Description of the Issue:

QuestID/ BossID:
Counterattack!
Instance:

What should happen:
Centaurs should spawn to fight, so you can take the banner. But instead nothing happens.

Faction: Horde/Alliance
Horde. Barrens quest from Regthar Deathgate

How to repoduce:

**Comment by Sockerkorn** [comment]
Did you talk to the quest guy and press the "I am ready" option? A lot of people miss that.

**Comment by Dreask** [comment]
Yeah i missed that, my bad.  It worked after trying again
