### ISSUE TITLE
Lordaeron shrine. 

### ISSUE THREAD

**Issue by Sockerkorn** [talamortis/azerothcore-classic#32]
Description of the Issue:
Lordaeron Shrine in EPL does absolutely nothing, infact i am not sure i know myself what it does. 
Found this though: http://www.wowhead.com/object=181682/lordaeron-shrine#comments
QuestID/ BossID:

Instance:

What should happen:

Faction: Horde/Alliance

How to repoduce:

**Comment by talamortis** [comment]
shrine is surpose to cast spell 30238 on the player once clicked.
