### ISSUE TITLE
Foror's Compendium of Dragon slaying

### ISSUE THREAD

**Issue by Dreask** [talamortis/azerothcore-classic#35]
Description of the Issue:
I didn't get the Elven blade, nor was it lootable anywhere at Lorekeeper Lydros in Dire Maul library

QuestID/ BossID:

Instance:
Dire Maul library
What should happen:
I should get "A dull and flat elven blade" that starts the next quest for "The Forging of Quel'Serrar"

Faction: Horde/Alliance
Horde

How to repoduce:

**Comment by talamortis** [comment]
please complete librem quests then let me know the outcome
