### ISSUE TITLE
Unusually high rate of pick pocket being resisted

### ISSUE THREAD

**Issue by fastphil007** [talamortis/azerothcore-classic#40]
Description of the Issue:
I have noticed a very HIGH rate of failure/resist of pick pocket while playing my rogue.  I've literally kept a tally of tries vs resist and it is approaching 90% resist rate.  It has become a bit frustrating because if they resist it puts you right into combat with them and nullyfying any sort of sneak attack.   Resisting is part of the game, i get that, but it should be 10% not 90%

How to repoduce:
Specifically i was in 1KN and picking to pockets of the centaur, but i have noticed the resist rate unusually high accross all mob types.

**Comment by talamortis** [comment]
Arc has tested this issue on a rogue, he has not come across this issue.

the working out for this is here 

https://github.com/talamortis/azerothcore-classic/blob/master/src/game/WorldHandlers/SpellEffects.cpp#L2508-L2521

**Comment by fastphil007** [comment]
That is interesting because i was just testing this again last night and I
am still getting resisted about 80+% of the time.  It was against equal lvl
mobs.    Against lower level mobs it fell to about 50% but that is still
way too high.  I dont understand why it is happening to me if things are
running correctly.

-Phil

**Comment by talamortis** [comment]
Arc was on a level 60, and pickpocketing level 54-59 elites a few resisted but he got more picks than resist

**Comment by fastphil007** [comment]
I am lvl 42 and pick pocketing lvl 41-44 mobs and just now got resisted 12
out of 17 times.     Maybe it evens out more at 60?   maybe it was because
the mobs were lower level than him?   Don't really know, but at this point
its kinda useless to pick pocket till 60 then  =\

**Comment by talamortis** [comment]
i will look more into this and check the rate and alter it as ive tested myself on local and i also think that its a little to high for resistance.

**Comment by fastphil007** [comment]
Thank you sir, i appreciate it  =)
