### ISSUE TITLE
Fargodep mine - boar 3.3.5

### ISSUE THREAD

**Issue by Ace-wildhammer** [talamortis/azerothcore-classic#44]
Not a big deal here, jsut found a "Stonetusk Boar" mob in "Fargodeep mine" zone

ROFL

![stonetusk](https://cloud.githubusercontent.com/assets/26637435/25202581/82bb6202-255e-11e7-9020-840193f38865.png)

**Comment by talamortis** [comment]
Thiis is a problem with the MMaps
