### ISSUE TITLE
Boss Amnennar the Coldbringer

### ISSUE THREAD

**Issue by talamortis** [talamortis/azerothcore-classic#5]
Description of the Issue:
Amnennar the Coldbringer does not spawn the adds. he also should summon 3 groups of adds at different % of hp, he is only spawning two groups:

Source: http://vanilla-wow.wikia.com/wiki/Amnennar_the_Coldbringer

QuestID/ BossID:
7358

Instance:
Razorfen Downs

What should happen:
He should summon 3 groups as prenerf to patch 2.3, he is summoning 2, they should also attack but instead they instantly disappear

Faction: Horde/Alliance
Both

How to repoduce:
Enter the instance and engage the creature

**Comment by Zuty** [comment]
Unable to ring the gong on him after the first wave.

**Comment by talamortis** [comment]
completely rescripted Amnennar the Coldbringer and also added prenerf.
